### ISSUE TITLE
Too many packages in the docker?

### ISSUE THREAD

**Issue by giabaio** [Bogdasayen/decision_trees_docker#1]
This is a `docker` I had created to include some packages that are probably irrelevant for your purposes here (like `xaringan` etc). Do you want me to clean the `install.R` file?

**Comment by giabaio** [comment]
In fact, you should tie that up with the main `R` script, to make sure that packages that are required (and you're calling with a `library(...)` command are installed through `install.R`...

HTH

**Comment by Bogdasayen** [comment]
Yes, feel free to remove packages that aren't likely to be relevant. The only ones I'm likely to need are xlsx, openxlsx, and bcea. I can add more if my code demonstration gets more ambitious.

**Comment by giabaio** [comment]
Can look into this later --- about to go to a meeting. The error message is probably to do with `binder` --- you could try and clear the cache, or wait a try again a bit later... It is not to do with the `Dockerfile` or the structure of this repo...

The "redundant" packages are also clearly indicated in the `install.R` file, so should be easy to clean up...

**Comment by Bogdasayen** [comment]
Yes, can wait till a bit later (presenting tomorrow morning).
I can clean up install.R that's no problem.
I'll let you know if binder starts working on its own!

**Comment by giabaio** [comment]
All seems to work - the binder loaded up and the script runs until the end... I've commented out some packages you don't need; there's nothing else in the script you need to install that isn't already in the main docker! I think you're good to go!
